[package]
name = "wafflemaker"
description = "WaffleHack's application deployment service"
version = "0.1.0"
authors = ["Alex Krantz <alex@krantz.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Utilities
serde = { version = "1.0", features = ["derive"] }

# Webhooks
base64 = "0.13.0"
hex = "0.4.3"
ring = { version = "0.16.20", default-features = false, features = ["std"] }
serde_json = "1.0"
