[package]
name = "wafflemaker"
description = "WaffleHack's application deployment service"
version = "0.1.0"
authors = ["Alex Krantz <alex@krantz.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Configuration
structopt = "0.3"
toml = "0.5"

# Error handling
anyhow = "1.0"

# Utilities
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.6", features = ["fs", "macros", "process", "rt", "rt-multi-thread"] }

# Webhooks
base64 = "0.13"
bytes = "1.0"
hex = "0.4"
ring = { version = "0.16", default-features = false, features = ["std"] }
serde_json = "1.0"
warp = { version = "0.3", default-features = false }
