[package]
name = "wafflemaker"
description = "WaffleHack's application deployment service"
version = "0.1.0"
authors = ["Alex Krantz <alex@krantz.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Utilities
serde = { version = "1.0", features = ["derive"] }

# Webhooks
serde_json = "1.0"
