version: "3"

services: 
  postgresql:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      default:
        ipv4_address: 172.96.0.2
  
  vault:
    image: vault:1.10.2
    ports:
      - "8200:8200"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=dev-token
    cap_add: 
      - IPC_LOCK
    volumes: 
      - ./docker/vault.hcl:/vault/config/vault.hcl
    networks:
      default:
        ipv4_address: 172.96.0.3
    depends_on:
      - postgresql

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      default:
        ipv4_address: 172.96.0.4

  setup:
    image: wafflehacks/wafflemaker:setup
    build: ./docker
    env_file: ./.dockerenv
    networks:
      default:
        ipv4_address: 172.96.0.64
    depends_on: 
      - vault

networks:
  default:
    ipam:
      config:
        - subnet: 172.96.0.0/16
