# The base server configuration
[server]
  # The port and address where server should listen to receive webhooks
  address = "127.0.0.1:8000"

  # The logging specification in the RUST_LOG format, can be overridden
  # by the RUST_LOG environment variable
  # Default: "info"
  log = "info"

  # The number of deployment processors to run
  workers = 2

# The deployment engine configuration
[deployment]
  # The base domain where services are deployed on
  domain = "wafflehacks.tech"

  # The type of deployer to use
  # Current supports:
  #   - docker (or any docker-compatible runtime)
  type = "docker"

  # How to connect to docker
  # Options:
  #   - local     connect via unix socket or local pipe
  #   - http      connect using unsecured HTTP
  #   - ssl       connect using HTTPS
  connection = "local"

  # The endpoint to connect to
  # Expects a path for `local`, and a URL for `http` or `ssl`
  endpoint = "unix:///var/run/docker.sock"

  # Where the server state should be stored
  state = "./state"

  # How long to wait in seconds for a request to complete
  timeout = 120

  # SSL only
  # The certificate authority to use
  #ca = "./ca.pem"

  # SSL only
  # The certificate to use
  #certificate = "./cert.pem"

  # SSL only
  # The certificate key to use
  #key = "./key.pem"

# Configuration for updating DNS records
[dns]
  # The Cloudflare zones that wafflemaker can modify
  zones = ["wafflehacks.tech"]

  # The public IP v4 and v6 addresses that the server can be accessed from
  [dns.addresses]
    # The public IPv4 address
    v4 = "127.0.0.1"

    # The public IPv6 address if the server supports it
    # v6 = "::1"

  # The credentials to authenticate with the Cloudflare API
  [dns.credentials]
    # The type of credentials to use
    # Options: user-key, user-token, service
    # See https://api.cloudflare.com/#getting-started-requests the differences
    type = "user-token"

    # The API token to authenticate with
    # Only used with `user-token`
    token = "ABCd-eFGHijKlmNoPQrsTUVWxyz0123456789-ab"

    # The email and corresponding API key to authenticate with
    # Only used with `user-key`
    # email = "example@example.com"
    # key = "1234567893feefc5f0q5000bfo0c3deadbeef"

    # The service token to authenticate with
    # key = "v1.0-e24fd090c02efcfecb4de8f4ff246fd5c75..."

# Configuration for the services repository
[git]
  # Where to clone the configuration repository to
  # The directory will be created if it does not exist
  clone_to = "./configuration"

  # The repository to pull configuration from
  repository = "WaffleHacks/waffles"

# Configuration for incoming webhooks
[webhooks]
  # DockerHub is used for notifying of updated images.
  # This must be webhook authentication token for HTTP basic auth
  # Must be in the format:
  #   <something>:<something>
  docker = "please-change:this-token"

  # GitHub for receiving service configuration updates.
  # This must be the webhook signing secret.
  github = "please-change-this-secret"
