# The base server configuration
[server]
  # The port and address where server should listen to receive webhooks
  address = "127.0.0.1:8000"

  # The logging specification in the RUST_LOG format, can be overridden
  # by the RUST_LOG environment variable
  # Default: "info"
  log = "info"

  # The number of deployment processors to run
  workers = 2

# The deployment engine configuration
[deployment]
  # The base domain where services are deployed on
  domain = "wafflehacks.tech"

  # The type of deployer to use
  # Current supports:
  #   - docker (or any docker-compatible runtime)
  type = "docker"

  # How to connect to docker
  # Options:
  #   - local     connect via unix socket or local pipe
  #   - http      connect using unsecured HTTP
  #   - ssl       connect using HTTPS
  connection = "local"

  # The endpoint to connect to
  # Expects a path for `local`, and a URL for `http` or `ssl`
  endpoint = "unix:///var/run/docker.sock"

  # How long to wait in seconds for a request to complete
  timeout = 120

  # SSL only
  # The certificate authority to use
  #ca = "./ca.pem"

  # SSL only
  # The certificate to use
  #certificate = "./cert.pem"

  # SSL only
  # The certificate key to use
  #key = "./key.pem"

# Configuration for the services repository
[git]
  # Where to clone the configuration repository to
  # The directory will be created if it does not exist
  clone_to = "./configuration"

  # The repository to pull configuration from
  repository = "WaffleHacks/waffles"

# Configuration for incoming webhooks
[webhooks]
  # DockerHub is used for notifying of updated images.
  # This must be webhook authentication token for HTTP basic auth
  # Must be in the format:
  #   <something>:<something>
  docker = "please-change:this-token"

  # GitHub for receiving service configuration updates.
  # This must be the webhook signing secret.
  github = "please-change-this-secret"
